// Mocks generated by Mockito 5.4.5 from annotations
// in club_metropolitan/test/unit/domain/cubit/all_activities/all_activities_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:club_metropolitan/data/services/data_service.dart' as _i2;
import 'package:club_metropolitan/domain/models/activity.dart' as _i4;
import 'package:club_metropolitan/domain/models/member.dart' as _i6;
import 'package:club_metropolitan/domain/models/trainer.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DataService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataService extends _i1.Mock implements _i2.DataService {
  MockDataService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get currentUserId =>
      (super.noSuchMethod(Invocation.getter(#currentUserId), returnValue: 0)
          as int);

  @override
  _i3.Future<List<_i4.Activity>> getActivities() =>
      (super.noSuchMethod(
            Invocation.method(#getActivities, []),
            returnValue: _i3.Future<List<_i4.Activity>>.value(<_i4.Activity>[]),
          )
          as _i3.Future<List<_i4.Activity>>);

  @override
  _i3.Future<List<_i4.Activity>> getAllActivities() =>
      (super.noSuchMethod(
            Invocation.method(#getAllActivities, []),
            returnValue: _i3.Future<List<_i4.Activity>>.value(<_i4.Activity>[]),
          )
          as _i3.Future<List<_i4.Activity>>);

  @override
  _i3.Future<List<_i5.Trainer>> getTrainers() =>
      (super.noSuchMethod(
            Invocation.method(#getTrainers, []),
            returnValue: _i3.Future<List<_i5.Trainer>>.value(<_i5.Trainer>[]),
          )
          as _i3.Future<List<_i5.Trainer>>);

  @override
  _i3.Future<List<_i6.Member>> getMembers() =>
      (super.noSuchMethod(
            Invocation.method(#getMembers, []),
            returnValue: _i3.Future<List<_i6.Member>>.value(<_i6.Member>[]),
          )
          as _i3.Future<List<_i6.Member>>);

  @override
  _i3.Future<String> getMemberName() =>
      (super.noSuchMethod(
            Invocation.method(#getMemberName, []),
            returnValue: _i3.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#getMemberName, []),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<List<_i4.Activity>> getUserActivities() =>
      (super.noSuchMethod(
            Invocation.method(#getUserActivities, []),
            returnValue: _i3.Future<List<_i4.Activity>>.value(<_i4.Activity>[]),
          )
          as _i3.Future<List<_i4.Activity>>);

  @override
  List<_i4.Activity> getUserActivitiesSync() =>
      (super.noSuchMethod(
            Invocation.method(#getUserActivitiesSync, []),
            returnValue: <_i4.Activity>[],
          )
          as List<_i4.Activity>);

  @override
  _i3.Future<bool> enrollInActivity(int? activityId) =>
      (super.noSuchMethod(
            Invocation.method(#enrollInActivity, [activityId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<_i4.Activity>> enrollUserInActivity(int? activityId) =>
      (super.noSuchMethod(
            Invocation.method(#enrollUserInActivity, [activityId]),
            returnValue: _i3.Future<List<_i4.Activity>>.value(<_i4.Activity>[]),
          )
          as _i3.Future<List<_i4.Activity>>);

  @override
  _i3.Future<bool> cancelEnrollment(int? activityId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelEnrollment, [activityId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<_i4.Activity>> cancelActivityForUser(
    _i4.Activity? activity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cancelActivityForUser, [activity]),
            returnValue: _i3.Future<List<_i4.Activity>>.value(<_i4.Activity>[]),
          )
          as _i3.Future<List<_i4.Activity>>);

  @override
  _i3.Future<bool> hasTimeConflict(_i4.Activity? activity) =>
      (super.noSuchMethod(
            Invocation.method(#hasTimeConflict, [activity]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i4.Activity?> getConflictingActivity(_i4.Activity? activity) =>
      (super.noSuchMethod(
            Invocation.method(#getConflictingActivity, [activity]),
            returnValue: _i3.Future<_i4.Activity?>.value(),
          )
          as _i3.Future<_i4.Activity?>);
}
